# Default values for chart

web:
  name: rating-web
  deployment: rating-web-prod
  versionLabel: prod
  replicas: 1
  image: "squillace.azurecr.io/squillace/steelthread"
  imageTag: "v6"
  serviceType: "LoadBalancer"
